### ISSUE TITLE
Add House of Representatives

### ISSUE THREAD

**Issue by benjarwar** [benjarwar/dial-congress#10]

**Comment by benjarwar** [comment]
@elgreg I've added the House of Reps, pulling/formatting JSON from the Google spreadsheet: https://github.com/benjarwar/dial-congress/tree/feature/add-house-of-reps

So far, it basically works! But when there's a lot of matches on the page, the processing is... significant. Testing http://www.house.gov/representatives/ took ~37 seconds; and it's render/paint blocking in the meantime. I'm not sure how to fix it without trying to chunk the number of names we're processing at a given time.

Another TODO is several reps (Grijalva, Gosar, Correa, etc) are not getting highlighted yet. Need to check out the JSON data.

**Comment by benjarwar** [comment]
I'm wondering if we should indicate "House" or "Senate" in the tooltip somehow. Might need to design it a bit more rather than using the default Tooltipster.

**Comment by elgreg** [comment]
Rad! I think House or Senate would make sense. But I can ping Josh too and ask what he thinks.

I'll try of other speedups. Nothing's coming to mind immediately.

**Comment by benjarwar** [comment]
@elgreg testing out some batch processing now in:

https://github.com/benjarwar/dial-congress/tree/feature/add-house-of-reps

Largely works, but lots more testing to be done. The MutationObserver stuff catches some many miniscule changes to the DOM. It looks like on certain SPAs (testing on multiple Facebook searches), the queue of "chunks" (objects containing a node, plus an array of found last names in the node, for future MarkJS marking) gets sizable.

Also, sorry if the logic is starting to get convoluted. Going to try and clean up, maybe add JSDocs, soon.

**Comment by benjarwar** [comment]
Bunch of improvements made to the [add reps branch](https://github.com/benjarwar/dial-congress/tree/feature/add-house-of-reps):

- Added JSDocs
- Refined some of the matching logic, simplified last names matching by removing word boundaries
- Added additional data for last/first/nickname name variations

There are a couple more issues to solve; added issues #12, #13, #14. But this is getting close to being PR-ready.
