### ISSUE TITLE
Remove wildcard middle name matching

### ISSUE THREAD

**Issue by benjarwar** [benjarwar/dial-congress#30]
- Add "middleNames" as an array to each congress person
- Refactor regex to look for permutations of first/nicknames + middle/nicknames + last name.

**Comment by benjarwar** [comment]
@elgreg big pass revising the regexp generation for adding middle names to the data:

https://github.com/benjarwar/dial-congress/compare/feature/middle-naming?expand=1

**Comment by molly-olmstead** [comment]
If they go by their middle name, would it be okay for me to double-list their middle name as both a middle name and nickname?

**Comment by molly-olmstead** [comment]
If the person goes by their middle name and that middle name has variations, would it be best to list the variations with the nickname and just the actual middle name as the middle name?

**Comment by benjarwar** [comment]
At the moment, the logic is going to be slightly different between the two fields.

**nicknames**: can optionally be surrounded by quotes. Also can *replace* the first name. e.g. ```Crazy``` in:
- Benjamin Crazy Warshaw
- Benjamin "Crazy" Warshaw
- "Crazy" Warshaw
- Crazy Warshaw

**middle names**: *must* occur between a first name or nickname *and* a last name. Will not be expected to be in quotes. e.g. ```Jared``` in:
- Benjamin Jared Warshaw
- Crazy Jared Warshaw
- "Crazy" Jared Warshaw

**Comment by benjarwar** [comment]
So, to answer your question, I suppose use your discretion. If we have something listed as a ```nickname```, but it's actually a ```middleName```, let's move it. I'm expecting that generally a person will only have one middle name, but multiple potential nicknames (but feel free to add multiple middle names if that case comes up).

**Comment by benjarwar** [comment]
And we probably shouldn't have duplication between the two fields.

**Comment by molly-olmstead** [comment]
I guess what I don't understand about that is that if we listed the name someone actually goes by as a middle name, but the middle name must occur between a first name and a last name, then that person would be missed. For example, Rep. Mark Walker's full name is Bradley Mark Walker. My instinct was to list Mark as a nickname, but if we just list it as a middle name, he wouldn't be flagged unless he was listed under Bradley, right?

**Comment by benjarwar** [comment]
Right so, in this case, I'd consider Mark to be a nickname, rather than middle name, since it commonly replaces his actual first name...

@elgreg how do you feel about all this? If we want to simplify on the data side, and only have a single ```nicknames``` field, which include middle names, we could go that route... but then we'd be creating a lot of extra match possibilities. Given:

```
{
  "firstName": "Mark",
  "lastName": "Walker",
  "nicknames": ["Bradley", "Fancypants"]
}
```

We'd be matching permutations like so:

```
Bradley Walker
Bradley Mark Walker
Bradley Fancypants Walker
Bradley Mark Fancypants Walker
Bradley Fancypants Mark Walker
Mark Walker
Fancypants Walker
Mark Fancypants Walker
Fancypants Mark Walker
```

With all nicknames optionally having quotes, e.g.:

```
Bradley "Mark" Walker
```

The downside with that is common middle names, like John, might cause excessive false positives. Consider this data:

```
{
  "firstName": "Mark",
  "lastName": "Smith",
  "middleNames": ["John"]
}
```

Under my current logic, we'll match ```Mark John Smith```, but not ```John Smith```. If we simplify and combine nickname with middle name logic, I worry we're opening the door for false positives whack-a-mole again...

**Comment by elgreg** [comment]
Yeah. The impression i got from Josh is that false positives are far worse
than a miss. I think that in the case where someone commonly goes by their
middle name, we should consider that a nickname. middleNames (and their
first characters optionally followed by a '.') can then safely be treated
as an optional separator between other names, but not as replacement.

**Comment by benjarwar** [comment]
Okay; cool. I think I agree, even if it makes @molly-olmstead's job a little harder in terms of deciding whether or not a middle name is a nickname. I think WikiPedia will be helpful here...

Also, I can add logic to the regex generation, and take any middle names, splice them to the first initial plus a period. This will save a lot of excess data entry. *Buuuut* we may wanna do a quick Google search. Given our current example, I searched for "Representative Bradley M Walker" and "Bradley M Walker" and came up with no results relating to the politician with "M" as initial. I think that's an even stronger indicator that, according to our app logic, we want "Mark" to be a nickname.

@molly-olmstead feel free to ping me direct with any other questionable cases. And thanks for all your assistance!

**Comment by benjarwar** [comment]
Fixed in https://github.com/benjarwar/dial-congress/pull/33.
